### ISSUE TITLE
Travis build matrix

### ISSUE THREAD

**Issue by johannkm** [ctring/SLOG#50]
Run tests on the combinations of environments (different remastering protocols, replication delay on/off, etc)

The different environments should build and test in parallel. 

I haven't fully looked into how this is done in travis, but I think it might involve:
- an initial stage that runs the dependency script
- the main stage, which uses multiple jobs for the combinations of environment settings

The various options are in [`CMakeLists.txt`](https://github.com/ctring/SLOG/blob/master/CMakeLists.txt). Currently the only relevant options for this are `REMASTER_PROTOCOL`, which is `SIMPLE` or `PER_KEY`, and `ENABLE_REPLICATION_DELAY`, `ON` or `OFF`

**Comment by vasantteja** [comment]
Hey this sounds interesting. Let me know if you need any help.

**Comment by johannkm** [comment]
@vasantteja thanks for reaching out! I'll get back to soon

**Comment by johannkm** [comment]
@vasantteja go for it if you'd like! I'll add more details in the description. We don't have a contributors guide yet but the process is standard, just tag me or @ctring in a pull request.
