### ISSUE TITLE
question on running SLOG on a single machine

### ISSUE THREAD

**Issue by CES-dengzeyuan** [ctring/SLOG#68]
Hi, I followed the steps in your readme to build the project. I would like to ask why there is no output while running a single-node demo, which is different from your sample result?

I think it should be the problem here (-address /tmp/slog). I would like to ask how the slog file in this tmp folder is generated.

Thank you!
![捕获](https://user-images.githubusercontent.com/46039524/146934772-b44d917a-10fc-4827-8ce5-cba6cec6db5e.PNG)

**Comment by ctring** [comment]
Hello. Thank you for trying this. I have made a few changes to the document and the example config file for it to work. 

The `/tmp/slog` file was created as part of [ZeroMQ IPC](http://api.zeromq.org/master:zmq-ipc). It seems I removed ipc protocol from the client at some point but didn't update the example configs.

**Comment by CES-dengzeyuan** [comment]
Thank you very much for your reply. 

I would like to ask if you can provide a single-node executable file that has been built. I am in China due to the firewall, even if I have used a proxy, the installation of third-party dependencies is often disconnected from github.

Is there any other more feasible method available, thank you！

![捕获](https://user-images.githubusercontent.com/46039524/147093767-e79a32ce-6b8f-4207-a4f9-3dbdbfb42aaa.PNG)

**Comment by CES-dengzeyuan** [comment]
I wrote an endless loop to rush the wall, and it succeeded.

I am a graduate student of Northeastern University. Recently, I have just started to study the direction of deterministic database. I am very interested in this direction.

If possible, I wonder if we can maintain academic exchanges by E-mail.

Finally, thank you very much for your help！

（My E-mail address is 2101704@stu.neu.edu.cn）

**Comment by ctring** [comment]
Great! Feel free to contact me at ctring@umd.edu
